name: Publish model schemata

on:
  # ATM, this is the closest trigger to a PR merging
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Need history for `git describe`
          path: dandischema

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dandischema
        run: python -m pip install .
        working-directory: dandischema

      - name: Checkout dandi/schema
        uses: actions/checkout@v2
        with:
          repository: dandi/schema
          path: schema
          token: ${{ secrets.DANDI_GITHUB_TOKEN }}

      - name: Generate model schemata
        run: python dandischema/tools/pubschemata.py schema/releases

      # Disabled to be reworked as discussed in
      # https://github.com/dandi/dandischema/issues/2
      # to be published only upon release of the dandischema
      #- name: Commit changes
      #  run: |
      #    git config --global user.email "team@dandiarchive.org"
      #    git config --global user.name "DANDI Bot"
      #
      #    git add releases
      #    if ! git diff --quiet --cached
      #    then git commit -m "Publish model schemata as of dandi-cli $(git -C ../dandi describe --tags)"
      #         git push
      #    else echo "No changes to commit"
      #    fi
      #  working-directory: schema

# vim:set sts=2:
